import { useContext } from "react"
import { RawMaterialContext } from "../itemContext/RawMaterialContext"
import Navbar from "./Navbar"
import { Download, FileText } from "lucide-react"
import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"

export default function StockReport() {

  const { material, productionHistory } = useContext(RawMaterialContext)

  /////////////////////////////////////////////////////
  // GENERATE PDF REPORT
  /////////////////////////////////////////////////////
  const generatePDF = () => {

    const doc = new jsPDF()

    /////////////////////////////////////////////////
    // TITLE
    /////////////////////////////////////////////////

    doc.setFontSize(20)
    doc.setTextColor(30, 64, 175)
    doc.text("Stock Report", 14, 20)

    const today = new Date().toLocaleDateString()

    doc.setFontSize(10)
    doc.setTextColor(100)
    doc.text(`Generated on: ${today}`, 14, 28)

    /////////////////////////////////////////////////
    // MATERIAL TABLE
    /////////////////////////////////////////////////

    doc.setFontSize(14)
    doc.setTextColor(0)
    doc.text("Current Materials", 14, 40)

    const materialHeaders = [["Material", "Quantity", "Unit", "Status"]]

    const materialRows = material.map((item) => {

      const status =
        Number(item.quantity) <= Number(item.minStock)
          ? "Low Stock"
          : "In Stock"

      return [item.item, item.quantity, item.unit, status]
    })

    autoTable(doc, {
      startY: 45,
      head: materialHeaders,
      body: materialRows,
      theme: "grid",
      styles: { fontSize: 10, cellPadding: 3 },
      headStyles: {
        fillColor: [59, 130, 246],
        textColor: 255,
        fontStyle: "bold",
      },
    })

    /////////////////////////////////////////////////
    // PRODUCTION TABLE
    /////////////////////////////////////////////////

    const finalY = doc.lastAutoTable?.finalY || 60

    doc.setFontSize(14)
    doc.setTextColor(0)
    doc.text("Daily Production", 14, finalY + 15)

    const productionHeaders = [["Recipe", "Quantity", "Date"]]

    const productionRows =
      productionHistory.length > 0
        ? productionHistory.map((p) => [p.recipe, p.quantity, p.date])
        : [["No production history", "", ""]]

    autoTable(doc, {
      startY: finalY + 20,
      head: productionHeaders,
      body: productionRows,
      theme: "grid",
      styles: { fontSize: 10, cellPadding: 3 },
      headStyles: {
        fillColor: [34, 197, 94],
        textColor: 255,
        fontStyle: "bold",
      },
    })

    /////////////////////////////////////////////////
    // SUMMARY
    /////////////////////////////////////////////////

    const summaryY = doc.lastAutoTable?.finalY + 15

    const totalMaterials = material.length

    const lowStockItems = material.filter(
      (item) => Number(item.quantity) <= Number(item.minStock)
    ).length

    const totalProduction = productionHistory.reduce(
      (sum, p) => sum + Number(p.quantity || 0),
      0
    )

    doc.setFontSize(12)
    doc.text("Summary", 14, summaryY)

    doc.setFontSize(10)

    doc.text(`• Total Materials: ${totalMaterials}`, 14, summaryY + 8)

    doc.text(`• Low Stock Items: ${lowStockItems}`, 14, summaryY + 16)

    doc.text(`• Total Production: ${totalProduction} units`, 14, summaryY + 24)

    /////////////////////////////////////////////////
    // FOOTER
    /////////////////////////////////////////////////

    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text("Generated by Peace-Flow Stock System", 14, 285)

    /////////////////////////////////////////////////
    // DOWNLOAD
    /////////////////////////////////////////////////

    doc.save("Stock_Report.pdf")
  }

  /////////////////////////////////////////////////////
  // STATUS COLOR
  /////////////////////////////////////////////////////

  const getStatusClass = (quantity, minStock) => {
    return Number(quantity) <= Number(minStock)
      ? "text-red-700 bg-red-100"
      : "text-green-700 bg-green-100"
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 p-6">

      <Navbar />

      <div className="max-w-6xl mx-auto">

        {/* HEADER */}

        <div className="flex justify-between items-center mb-6 py-20">

          <h1 className="text-3xl font-bold text-blue-800 flex items-center gap-2">
            <FileText className="text-blue-600" />
            Stock Report
          </h1>

          <button
            onClick={generatePDF}
            className="flex items-center gap-2 bg-blue-600 text-white px-6 py-2 rounded-lg hover:bg-blue-700 transition"
          >
            <Download size={18} />
            Download PDF Report
          </button>

        </div>

        {/* MATERIAL TABLE */}

        <div className="bg-white rounded-xl shadow-xl p-6 mb-6">

          <h2 className="text-xl font-semibold mb-4">
            Current Materials
          </h2>

          <div className="overflow-x-auto">

            <table className="w-full">

              <thead>

                <tr className="bg-blue-600 text-white">

                  <th className="p-3 text-left">Material</th>
                  <th className="p-3 text-left">Quantity</th>
                  <th className="p-3 text-left">Unit</th>
                  <th className="p-3 text-left">Status</th>

                </tr>

              </thead>

              <tbody>

                {material.map((item, index) => (

                  <tr key={index} className="border-b">

                    <td className="p-3 font-medium">{item.item}</td>

                    <td className="p-3">{item.quantity}</td>

                    <td className="p-3">{item.unit}</td>

                    <td className="p-3">

                      <span
                        className={`px-3 py-1 rounded-full text-sm font-medium ${getStatusClass(
                          item.quantity,
                          item.minStock
                        )}`}
                      >
                        {Number(item.quantity) <= Number(item.minStock)
                          ? "Low Stock"
                          : "In Stock"}
                      </span>

                    </td>

                  </tr>

                ))}

              </tbody>

            </table>

          </div>

        </div>

        {/* PRODUCTION TABLE */}

        <div className="bg-white rounded-xl shadow-xl p-6">

          <h2 className="text-xl font-semibold mb-4">
            Daily Production
          </h2>

          <div className="overflow-x-auto">

            <table className="w-full">

              <thead>

                <tr className="bg-green-600 text-white">

                  <th className="p-3 text-left">Recipe</th>
                  <th className="p-3 text-left">Quantity</th>
                  <th className="p-3 text-left">Date</th>

                </tr>

              </thead>

              <tbody>

                {productionHistory.length > 0 ? (

                  productionHistory.map((p, index) => (

                    <tr key={index} className="border-b">

                      <td className="p-3">{p.recipe}</td>

                      <td className="p-3">{p.quantity}</td>

                      <td className="p-3">{p.date}</td>

                    </tr>

                  ))

                ) : (

                  <tr>

                    <td colSpan="3" className="text-center p-6 text-gray-500">
                      No production history available
                    </td>

                  </tr>

                )}

              </tbody>

            </table>

          </div>

        </div>

      </div>

    </div>
  )
}